version: '3.4'

services:
      library:
        image: library
        read_only: false
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
          - 3333:3333
        volumes:
          - .:usr/src/app
          - usr/src/app/node_modules/
        environment:
          NODE_ENV: production
