name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i

      - name: auth login tests
      - run: npm run auth-login:test:ci
      - run: npm run auth-login:e2e:production

      - name: Auth register tests
      - run: npm run auth-register:test:ci
      - run: npm run auth-register:e2e:production

      - name: books search tests
      - run: npm run books-search:test:ci
      - run: npm run books-search:e2e:production

#      Books list tests
      - run: npm run books-list:test:ci

#     Build apps
      - run: npm run build:api:production
      - run: npm run build:web:production
