name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i

      - name: auth login unit test
        run: npm run auth-login:test:ci

      - name: auth login e2e test
        run: npm run auth-login:e2e:production

      - name: auth register unit test
        run: npm run auth-register:test:ci

      - name: auth register e2e test
        run: npm run auth-register:e2e:production

      - name: book search unit test
        run: npm run books-search:test:ci

      - name: book search e2e test
        run: npm run books-search:e2e:production

      - name: book list unit test
        run: npm run books-list:test:ci